name: version
on:
  push:
    branches:
      - main
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix:  'v'
        minor-wording:  'MINOR,feat,chore,build,ci,docs,style'
        major-wording:  'MAJOR,cut-major'
        patch-wording:  'fix,fixes,patch' 